CREATE TYPE "ArtifactProvider" AS ENUM (
  'aws_s3',
  'azure_blob',
  'gcs',
  'minio',
  'filesystem'
);

CREATE TYPE "ArtifactStatus" AS ENUM (
  'active',
  'soft_deleted',
  'expired'
);

CREATE TYPE "ArtifactRole" AS ENUM (
  'calibration',
  'misc',
  'logs',
  'report',
  'model',
  'pointcloud',
  'img'
);

CREATE TYPE "ArtifactContentType" AS ENUM (
  'application_json',
  'text_plain',
  'text_csv',
  'image_png',
  'image_jpeg',
  'application_pdf',
  'application_zip'
);

CREATE TABLE "Accessor" (
  "accessor_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "login" varchar UNIQUE NOT NULL,
  "name" varchar NOT NULL,
  "description" varchar,
  "role_id" integer NOT NULL,
  "password_hash" varchar NOT NULL,
  "password_last_changed" timestamp,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "Roles" (
  "role_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" varchar,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "Manufacturer" (
  "manufacturer_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" varchar,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "created_by_accessor" integer NOT NULL
);

CREATE TABLE "Artifacts" (
  "artifact_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uri" text NOT NULL,
  "storage_provider" "ArtifactProvider" NOT NULL,
  "content_type" "ArtifactContentType",
  "bytes" bigint,
  "etag_or_version" varchar,
  "sha256_hex" char(64) UNIQUE,
  "schema_uri" text,
  "schema_version" varchar,
  "status" "ArtifactStatus" NOT NULL DEFAULT 'active',
  "retention_until" timestamp,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "created_by_accessor" integer NOT NULL
);

CREATE TABLE "Effectors" (
  "effector_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" varchar,
  "metadata_id" integer,
  "tc_position" integer UNIQUE,
  "manufacturer_id" integer NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "created_by_accessor" integer NOT NULL
);

CREATE TABLE "Robots" (
  "robot_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" varchar,
  "metadata_id" integer,
  "manufacturer_id" integer NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "created_by_accessor" integer NOT NULL
);

CREATE TABLE "Operation_Types" (
  "operation_type_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" varchar,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "created_by_accessor" integer NOT NULL
);

CREATE TABLE "Operations" (
  "operation_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "operation_type_id" integer NOT NULL,
  "effector_id" integer NOT NULL,
  "robot_id" integer NOT NULL,
  "status" varchar NOT NULL,
  "status_description" varchar,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "created_by_accessor" integer NOT NULL
);

CREATE TABLE "OperationArtifact" (
  "operation_artifact_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "operation_id" integer NOT NULL,
  "artifact_id" integer NOT NULL,
  "artifact_role" "ArtifactRole" NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "created_by_accessor" integer NOT NULL
);

CREATE TABLE "RobotArtifact" (
  "robot_artifact_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "robot_id" integer NOT NULL,
  "artifact_id" integer NOT NULL,
  "artifact_role" "ArtifactRole" NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "created_by_accessor" integer NOT NULL
);

CREATE TABLE "EffectorArtifact" (
  "effector_artifact_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "effector_id" integer NOT NULL,
  "artifact_id" integer NOT NULL,
  "artifact_role" "ArtifactRole" NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "created_by_accessor" integer NOT NULL
);

COMMENT ON COLUMN "Accessor"."login" IS 'unique login / username';

COMMENT ON COLUMN "Accessor"."name" IS 'presented name';

COMMENT ON COLUMN "Accessor"."password_hash" IS 'bcrypt hash (with salt), ie. $2b$12$...';

COMMENT ON COLUMN "Artifacts"."uri" IS 'ie. s3://bucket/key';

COMMENT ON COLUMN "Artifacts"."sha256_hex" IS 'integrity + deduplication';

COMMENT ON COLUMN "OperationArtifact"."artifact_role" IS 'artifact type (calibration, output, …)';

COMMENT ON COLUMN "RobotArtifact"."artifact_role" IS 'artifact type (calibration, output, …)';

COMMENT ON COLUMN "EffectorArtifact"."artifact_role" IS 'artifact type (calibration, output, …)';

ALTER TABLE "Accessor" ADD FOREIGN KEY ("role_id") REFERENCES "Roles" ("role_id");

ALTER TABLE "Manufacturer" ADD FOREIGN KEY ("created_by_accessor") REFERENCES "Accessor" ("accessor_id");

ALTER TABLE "Artifacts" ADD FOREIGN KEY ("created_by_accessor") REFERENCES "Accessor" ("accessor_id");

ALTER TABLE "Effectors" ADD FOREIGN KEY ("metadata_id") REFERENCES "Artifacts" ("artifact_id");

ALTER TABLE "Effectors" ADD FOREIGN KEY ("manufacturer_id") REFERENCES "Manufacturer" ("manufacturer_id");

ALTER TABLE "Effectors" ADD FOREIGN KEY ("created_by_accessor") REFERENCES "Accessor" ("accessor_id");

ALTER TABLE "Robots" ADD FOREIGN KEY ("metadata_id") REFERENCES "Artifacts" ("artifact_id");

ALTER TABLE "Robots" ADD FOREIGN KEY ("manufacturer_id") REFERENCES "Manufacturer" ("manufacturer_id");

ALTER TABLE "Robots" ADD FOREIGN KEY ("created_by_accessor") REFERENCES "Accessor" ("accessor_id");

ALTER TABLE "Operation_Types" ADD FOREIGN KEY ("created_by_accessor") REFERENCES "Accessor" ("accessor_id");

ALTER TABLE "Operations" ADD FOREIGN KEY ("operation_type_id") REFERENCES "Operation_Types" ("operation_type_id");

ALTER TABLE "Operations" ADD FOREIGN KEY ("effector_id") REFERENCES "Effectors" ("effector_id");

ALTER TABLE "Operations" ADD FOREIGN KEY ("robot_id") REFERENCES "Robots" ("robot_id");

ALTER TABLE "Operations" ADD FOREIGN KEY ("created_by_accessor") REFERENCES "Accessor" ("accessor_id");

ALTER TABLE "OperationArtifact" ADD FOREIGN KEY ("operation_id") REFERENCES "Operations" ("operation_id");

ALTER TABLE "OperationArtifact" ADD FOREIGN KEY ("artifact_id") REFERENCES "Artifacts" ("artifact_id");

ALTER TABLE "OperationArtifact" ADD FOREIGN KEY ("created_by_accessor") REFERENCES "Accessor" ("accessor_id");

ALTER TABLE "RobotArtifact" ADD FOREIGN KEY ("robot_id") REFERENCES "Robots" ("robot_id");

ALTER TABLE "RobotArtifact" ADD FOREIGN KEY ("artifact_id") REFERENCES "Artifacts" ("artifact_id");

ALTER TABLE "RobotArtifact" ADD FOREIGN KEY ("created_by_accessor") REFERENCES "Accessor" ("accessor_id");

ALTER TABLE "EffectorArtifact" ADD FOREIGN KEY ("effector_id") REFERENCES "Effectors" ("effector_id");

ALTER TABLE "EffectorArtifact" ADD FOREIGN KEY ("artifact_id") REFERENCES "Artifacts" ("artifact_id");

ALTER TABLE "EffectorArtifact" ADD FOREIGN KEY ("created_by_accessor") REFERENCES "Accessor" ("accessor_id");
